version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    - "2888"
    - "3888"

  portainer:
    image: portainer/portainer
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  kafka-1:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zookeeper

  hello-consumer:
    image: consumer:latest
    depends_on:
    - kafka-1

  hello-producer:
    image: producer:latest
    depends_on:
    - kafka-1
    - hello-consumer

